version: '3'

services:
  node:
    image: xmtp/node-go:latest
    platform: linux/amd64
    command:
      - --ws
      - --store.enable
      - --store.db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --store.reader-db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --ws-port=9001
      - --wait-for-db=30s
      - --api.authn.enable
    ports:
      - 5555:5555
      - 5556:5556
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
    ports:
      - 25432:5432
