name: Deploy Nodes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: xmtpeng
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Git Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Deploy
        run: |
          export DOCKER_IMAGE_TAG=latest
          IMAGE_TO_DEPLOY=xmtp/notifications-server@$(dev/push)
          echo Successfully pushed $IMAGE_TO_DEPLOY
